import {
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  FETCH_CAT_REQUEST,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  ADOPT_CAT_ERROR,
} from './cat';

import {
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  FETCH_DOG_REQUEST,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  ADOPT_DOG_ERROR,
} from './dog';

